/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ahmed
 */

import java.io.*;
import javax.swing.JOptionPane;
import java.util.*;
public class Login_page extends javax.swing.JFrame {

    /**
     * Creates new form Login_page
     */
    public Login_page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_check = new javax.swing.JButton();
        btn_manager = new javax.swing.JButton();
        btn_receptionist = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_check.setText("Check");
        btn_check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_checkActionPerformed(evt);
            }
        });

        btn_manager.setText("Manaeger");
        btn_manager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_managerActionPerformed(evt);
            }
        });

        btn_receptionist.setText("Receptionist");
        btn_receptionist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_receptionistActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(btn_check))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_receptionist, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                            .addComponent(btn_manager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(btn_manager)
                .addGap(35, 35, 35)
                .addComponent(btn_receptionist)
                .addGap(48, 48, 48)
                .addComponent(btn_check)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_checkActionPerformed
        // TODO add your handling code here:
//        try {
//            File file=new File("login.txt");
//            if(!file.exists()){
//                file.createNewFile();
//            }
//            
//            BufferedReader br=new BufferedReader(new FileReader(file));
//            String s=br.readLine();
//            String[] str = new String[10];
//           str= s.split("@");
//           if(str[0].equals(txt_username.getText())&&str[1].equals(txt_password.getText())){
//               JOptionPane.showMessageDialog(this, "right username and password","ok",JOptionPane.ERROR_MESSAGE);
//           }
//           else{
//               JOptionPane.showMessageDialog(this, "error","ok",JOptionPane.ERROR_MESSAGE);
//           }
//            
//        } catch (IOException e) {
//            
//        }
//        boolean found=false;
//        try {
//            Scanner in=new Scanner(new File("manager_data.txt"));
//            Scanner in2=new Scanner(new File("receptionist_data.txt"));
//            ArrayList<String> manager=new ArrayList<String>();
//            ArrayList<String> receptionist=new ArrayList<String>();
//            String[] str = new String[10];
//            String s;
//            while (in.hasNext()) {
//                manager.add(in.nextLine());
//                
//            }
//            for(int i=0;i<receptionist.size();i++){
//                s=manager.get(i);
//                str= s.split("@");
//                if(str[0].equals(txt_username.getText())&&str[1].equals(txt_password.getText())){
//                    JOptionPane.showMessageDialog(this, "login successfully as receptionist", "ok", JOptionPane.INFORMATION_MESSAGE);
//                    found=true;
//                    receptionist man=new Receptionist();
//                    man.show();
//                    dispose();
//                }
//            }
//            for(int i=0;i<re.size();i++){
//                s=manager.get(i);
//                str= s.split("@");
//                if(str[0].equals(txt_username.getText())&&str[1].equals(txt_password.getText())){
//                    JOptionPane.showMessageDialog(this, "login successfully as manager", "ok", JOptionPane.INFORMATION_MESSAGE);
//                    found=true;
//                    Manager_form man=new Manager_form();
//                    man.show();
//                    dispose();
//                }
//            }
//        } catch (Exception e) {
//            
//        }
//        Manager_form man=new Manager_form();
//        man.show();
//        dispose();
    }//GEN-LAST:event_btn_checkActionPerformed

    private void btn_managerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_managerActionPerformed
        // TODO add your handling code here:
        manager_login manager=new manager_login();
        manager.show();
        dispose();
        
    }//GEN-LAST:event_btn_managerActionPerformed

    private void btn_receptionistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_receptionistActionPerformed
        // TODO add your handling code here:
        receptionist_login receptionist=new receptionist_login();
        receptionist.show();
        dispose();
    }//GEN-LAST:event_btn_receptionistActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_check;
    private javax.swing.JButton btn_manager;
    private javax.swing.JButton btn_receptionist;
    // End of variables declaration//GEN-END:variables
}
