
import java.util.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hossam eldien moham
 */
public class Receptionist_form extends javax.swing.JFrame {

    /**
     * Creates new form Receptionist_form
     */
    public Receptionist_form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_addResident = new javax.swing.JButton();
        txt_deleteResident = new javax.swing.JButton();
        txt_editResidentData = new javax.swing.JButton();
        txt_assignResidentToRoom = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt_addResident.setText("Add resident");
        txt_addResident.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_addResidentActionPerformed(evt);
            }
        });

        txt_deleteResident.setText("Delete resident");
        txt_deleteResident.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_deleteResidentActionPerformed(evt);
            }
        });

        txt_editResidentData.setText("Edit resident data");
        txt_editResidentData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_editResidentDataActionPerformed(evt);
            }
        });

        txt_assignResidentToRoom.setText("Assign resident to room");

        btn_back.setText("Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_editResidentData)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(txt_assignResidentToRoom))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_addResident)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_deleteResident)))
                .addGap(110, 110, 110))
            .addGroup(layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(btn_back)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_deleteResident)
                    .addComponent(txt_addResident))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_editResidentData)
                    .addComponent(txt_assignResidentToRoom))
                .addGap(67, 67, 67)
                .addComponent(btn_back)
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    ArrayList<Receptionist>re=new ArrayList<>();
    
    private void txt_editResidentDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_editResidentDataActionPerformed
        // TODO add your handling code here:
        edit_resident edit=new edit_resident();
        edit.show();
        dispose();
    }//GEN-LAST:event_txt_editResidentDataActionPerformed

    private void txt_addResidentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_addResidentActionPerformed
        // TODO add your handling code here:
        add_resident add=new add_resident();
        add.show();
        dispose();
    }//GEN-LAST:event_txt_addResidentActionPerformed

    private void txt_deleteResidentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_deleteResidentActionPerformed
        // TODO add your handling code here:
        delete_resident delete=new delete_resident();
        delete.show();
        dispose();
    }//GEN-LAST:event_txt_deleteResidentActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        receptionist_login rec=new receptionist_login();
        rec.show();
        dispose();
        
    }//GEN-LAST:event_btn_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Receptionist_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Receptionist_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Receptionist_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Receptionist_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Receptionist_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton txt_addResident;
    private javax.swing.JButton txt_assignResidentToRoom;
    private javax.swing.JButton txt_deleteResident;
    private javax.swing.JButton txt_editResidentData;
    // End of variables declaration//GEN-END:variables
}
